stages:
  - deploy

deploy_projet:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client git
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_SERVER" >> ~/.ssh/known_hosts
  script:
    - >
      ssh $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH &&
      git pull origin main &&
      composer install --no-dev --optimize-autoloader &&
      if [ -f package.json ]; then npm install && npm run build; fi &&
      php artisan migrate --force &&
      chown -R www-data:www-data storage bootstrap/cache &&
      chmod -R 775 storage bootstrap/cache"
  only:
    - main
